### ISSUE TITLE
Remap and/or disable writing mode?

### ISSUE THREAD

**Issue by bsradcliffe** [krismuniz/minimo#13]
Hey Kris,

As a power user, I'm relying on `Command (⌘) + ...` shortcuts to navigate between tabs frequently. `Command (⌘)` sees a lot of traffic from me, so as a result, I'm curious if there's an option to remap keys or disable writing mode functionality for the extension to prevent myself and others from unintentionally triggering it?

**Comment by krismuniz** [comment]
Keyboard shortcut mapping is definitely something in the roadmap!

For now, if you don't use writing mode at all, you can add this custom CSS:

```css
/* prevent editor from appearing */
#editor-container {
  display: none;
}

/* prevents awkward mode switch animation */
.layout {
  animation: none;
}
```
