### ISSUE TITLE
Have daily changing image backgrounds

### ISSUE THREAD

**Issue by mistermantas** [krismuniz/minimo#19]
It’s one cool feature of Momentum that I like, although I hate that the images sometimes make the text hard to read, and some images are somewhat annoying, so a skip button with all that would be grand.

Just a suggestion!

**Comment by rogatty** [comment]
@mistermantas until it's implemented you can use custom CSS like this:
```
body {
  background-image: url('https://picsum.photos/1920/1080');
}

.layout {
  background-color: rgba(0, 0, 0, 0.2);
}
```
When an image is annoying or makes the text hard to read, just refresh.

**Comment by mistermantas** [comment]
here are my changes - i used unsplash

(much more than just the background image.)

```css
* { font-family: 'Inter' !important; letter-spacing: 0.5px; text-shadow: 0 4px 32px rgba(0,0,0,0.5); }

body {
  background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.25)), url(https://source.unsplash.com/random/1280x720)
}
.status { display: none; }
.time { font-size: 6rem; font-weight: 800; }
.date { font-size: 3rem; font-weight: 500; } 

.time-box { align-self: flex-end; text-align: left; margin-left: 5vw }

.shortcut { padding-right: 36px; margin-right: 0; border-right: 1px solid #aaa; font-weight: 500; color: #aaa; }
```
